import { RouterError } from "./errors.js";
import type { CatalogModel, CatalogSnapshot, ModelAlias } from "./types.js";
const nowIso = () => new Date().toISOString();
export class CatalogStore { private snapshot: CatalogSnapshot | null = null; constructor(initial?: CatalogSnapshot | null) { this.snapshot = initial ?? null; } getFresh(now = new Date()): CatalogSnapshot | null { if (!this.snapshot) return null; const age = now.getTime() - Date.parse(this.snapshot.fetchedAt); return age >= 0 && age <= 6 * 60 * 60 * 1000 && this.snapshot.status === "success" ? this.snapshot : null; } set(snapshot: CatalogSnapshot): void { this.snapshot = snapshot; } }
export function fakeCatalog(): CatalogSnapshot { const model: CatalogModel = { provider: "fake", modelId: "free-text", fetchedAt: nowIso(), sourceStatus: "success", capabilities: ["text", "streaming", "image_generation"], contextLimit: 8192, prices: { prompt: 0, completion: 0, image: 0 } }; return { provider: "fake", fetchedAt: model.fetchedAt, status: "success", sourceVersion: "fake", sourceResponseHash: "0".repeat(64), models: [model] }; }
export function isEligible(model: CatalogModel, capability: "text" | "image_generation", now = new Date()): boolean { const age = now.getTime() - Date.parse(model.fetchedAt); return model.sourceStatus === "success" && age >= 0 && age <= 6 * 60 * 60 * 1000 && model.capabilities.includes(capability) && (capability === "text" ? model.prices.prompt === 0 && model.prices.completion === 0 : model.prices.image === 0); }
export function candidatesFor(snapshot: CatalogSnapshot | null, alias: ModelAlias, capability: "text" | "image_generation", now = new Date()): CatalogModel[] { if (!snapshot) return []; return snapshot.models.filter((model) => isEligible(model, capability, now)).sort((a, b) => a.modelId.localeCompare(b.modelId)); }
export async function refreshCatalog(url: string, fetchImpl: typeof fetch = fetch): Promise<CatalogSnapshot> { const response = await fetchImpl(url, { headers: { accept: "application/json" } }); if (!response.ok) return { provider: "openrouter", fetchedAt: nowIso(), status: "failure", sourceVersion: "unknown", sourceResponseHash: "0".repeat(64), models: [], errorCode: "ORIN_CATALOG_UNAVAILABLE" }; const raw = await response.text(); const parsed = JSON.parse(raw) as { data?: Array<Record<string, unknown>> }; const models = (parsed.data ?? []).map((item) => ({ provider: "openrouter", modelId: String(item.id ?? ""), fetchedAt: nowIso(), sourceStatus: "success" as const, capabilities: ["text", "streaming"], contextLimit: Number(item.context_length ?? 0), prices: { prompt: Number((item.pricing as Record<string, unknown> | undefined)?.prompt ?? NaN), completion: Number((item.pricing as Record<string, unknown> | undefined)?.completion ?? NaN), image: null } })).filter((model) => model.modelId); return { provider: "openrouter", fetchedAt: nowIso(), status: "success", sourceVersion: "openrouter", sourceResponseHash: (await import("node:crypto")).createHash("sha256").update(raw).digest("hex"), models }; }
export function requireCandidates(snapshot: CatalogSnapshot | null, alias: ModelAlias, capability: "text" | "image_generation"): CatalogModel[] { const candidates = candidatesFor(snapshot, alias, capability); if (!candidates.length) throw new RouterError("ORIN_PROVIDER_EXHAUSTED", "No eligible zero-price provider is currently available.", true); return candidates; }
